//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZHost.CustomUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZHost.CustomUI.LocStringResources", typeof(LocStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual depth.
        /// </summary>
        internal static string _ActualDepth {
            get {
                return ResourceManager.GetString("_ActualDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis of.
        /// </summary>
        internal static string _AnalysisOf {
            get {
                return ResourceManager.GetString("_AnalysisOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to clear ALL application logs?.
        /// </summary>
        internal static string _ClearLogsPrompt {
            get {
                return ResourceManager.GetString("_ClearLogsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks saved. Do you want to clear tracks?.
        /// </summary>
        internal static string _ClearTracksAfterSavePrompt {
            get {
                return ResourceManager.GetString("_ClearTracksAfterSavePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to clear tracks?.
        /// </summary>
        internal static string _ClearTracksPrompt {
            get {
                return ResourceManager.GetString("_ClearTracksPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string _Close {
            get {
                return ResourceManager.GetString("_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string _Collapse {
            get {
                return ResourceManager.GetString("_Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entries were deleted.
        /// </summary>
        internal static string _EntriesWereDeleted {
            get {
                return ResourceManager.GetString("_EntriesWereDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string _Error {
            get {
                return ResourceManager.GetString("_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        internal static string _Expand {
            get {
                return ResourceManager.GetString("_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string _Information {
            get {
                return ResourceManager.GetString("_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is complete.
        /// </summary>
        internal static string _IsComplete {
            get {
                return ResourceManager.GetString("_IsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log files.
        /// </summary>
        internal static string _LogFiles {
            get {
                return ResourceManager.GetString("_LogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log restarted.
        /// </summary>
        internal static string _LogRestarted {
            get {
                return ResourceManager.GetString("_LogRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string _Question {
            get {
                return ResourceManager.GetString("_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote address change.
        /// </summary>
        internal static string _RemoteAddressChange {
            get {
                return ResourceManager.GetString("_RemoteAddressChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote command.
        /// </summary>
        internal static string _RemoteCommand {
            get {
                return ResourceManager.GetString("_RemoteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to reset settings to defaults?.
        /// </summary>
        internal static string _ResetToDefaultSettingsPrompt {
            get {
                return ResourceManager.GetString("_ResetToDefaultSettingsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responder zero depth adjust.
        /// </summary>
        internal static string _ResponderZeroDepthAdjust {
            get {
                return ResourceManager.GetString("_ResponderZeroDepthAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to restart current log?.
        /// </summary>
        internal static string _RestartLogPrompt {
            get {
                return ResourceManager.GetString("_RestartLogPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salinity.
        /// </summary>
        internal static string _Salinity {
            get {
                return ResourceManager.GetString("_Salinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save tracks as....
        /// </summary>
        internal static string _SaveTracksAs {
            get {
                return ResourceManager.GetString("_SaveTracksAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a log file to emulate....
        /// </summary>
        internal static string _SelectALogFileToEmulate {
            get {
                return ResourceManager.GetString("_SelectALogFileToEmulate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set actual station depth.
        /// </summary>
        internal static string _SetActualStationDepth {
            get {
                return ResourceManager.GetString("_SetActualStationDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string _Settings {
            get {
                return ResourceManager.GetString("_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved. Do you want to restart application to apply?.
        /// </summary>
        internal static string _SettingsSaveRestartPrompt {
            get {
                return ResourceManager.GetString("_SettingsSaveRestartPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound speed.
        /// </summary>
        internal static string _SoundSpeed {
            get {
                return ResourceManager.GetString("_SoundSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station depth is not enough.
        /// </summary>
        internal static string _StationDepthIsNotEnough {
            get {
                return ResourceManager.GetString("_StationDepthIsNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station info.
        /// </summary>
        internal static string _StationInfo {
            get {
                return ResourceManager.GetString("_StationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string _Warning {
            get {
                return ResourceManager.GetString("_Warning", resourceCulture);
            }
        }
    }
}
